### ISSUE TITLE
Please check code `def __init__(self, options)` at `HiddenLayers` in `utils/model_utils.py`

### ISSUE THREAD

**Issue by ByungSun** [AstraZeneca/SubTab#11]
I think `HiddenLayers` class code have wrong line.

This is Wrong code : 
```{python}
class HiddenLayers(nn.Module):
    def __init__(self, options):
        (...omission...)
        for i in range(1, len(dims) - 1): # <--- It's wrong code.
            ....
```

I think you need to correct code like below.
```{python}
class HiddenLayers(nn.Module):
    def __init__(self, options):
        (...omission...)
        for i in range(1, len(dims)): # <--- It's correct code.
            ....
```

Please check this code and I want your feedback.

Thank you.

**Comment by talipucar** [comment]
Hi ByungSun,

Thanks for your feedback.  Actually, the code is not wrong. The last dimension is intentionally left out so that it can be used separately within AEWrapper class. This is to give some flexibility on how we can use the last layer. The best way to see what is going on is to look at model architectures printed on the command line at the beginning of the training. 

You can also modify the code in the way that fits into your preference. I will close the issue, but if you have any follow-up question, please feel free to re-open it.
