### ISSUE TITLE
Do we need to define continuous and categorical features explicitly in mix type dataset?

### ISSUE THREAD

**Issue by monk1337** [AstraZeneca/SubTab#12]
Do we need to define continuous and categorical features explicitly in mix type dataset?

**Comment by talipucar** [comment]
In this work, we don't make any assumptions about the underlying data. So, you don't need to define them explicitly. However, you can always choose to treat categorical and continuous features differently if you prefer it.

I will close this issue, but feel free to re-open it, or open another one if/when you have any further questions.

**Comment by monk1337** [comment]
"you can always choose to treat categorical and continuous features differently if you prefer it." how? if there any option in the model setting?

**Comment by talipucar** [comment]
For example, you can choose to add different type of noise to the features based on whether they are categorical or continuous. Or, you can add embedding layer for categorical features, and use their embeddings rather than raw categorical features. And so on...it is really up to your imagination.

You need to customise the code to do any of these things mentioned above. But, it should be fairly straightforward.

**Comment by monk1337** [comment]
Thank you for your reply, It would be really helpful if you could add UCI Adult Income dataset settings for train and test.

**Comment by talipucar** [comment]
UCI Adult dataset is publicly available, and well-studied dataset with separate train and test sets. Please download it from UCI website. I will assume that this issue is completed now.
